import { Rocket, Users, Target, TrendingUp, Zap, CreditCard, ArrowRight, Sparkles } from 'lucide-react'

interface PaywallProps {
    /** Total leads generated by this user */
    leadsGenerated: number
    /** Number of campaigns created */
    campaignsCreated: number
    /** Hot leads (score >= 80) */
    hotLeads: number
    /** Messages generated (optional — defaults to estimate from leads) */
    messagesGenerated?: number
}

export function UpgradePaywall({
    leadsGenerated,
    campaignsCreated,
    hotLeads,
    messagesGenerated,
}: PaywallProps) {
    const estimatedMessages = messagesGenerated ?? Math.round(leadsGenerated * 0.3)

    const achievements = [
        {
            icon: Users,
            value: leadsGenerated,
            label: 'Leads discovered',
            color: 'text-blue-600 bg-blue-50',
        },
        {
            icon: Target,
            value: hotLeads,
            label: 'Hot opportunities',
            color: 'text-orange-600 bg-orange-50',
        },
        {
            icon: Sparkles,
            value: estimatedMessages,
            label: 'Messages crafted',
            color: 'text-indigo-600 bg-indigo-50',
        },
        {
            icon: Rocket,
            value: campaignsCreated,
            label: 'Campaigns launched',
            color: 'text-emerald-600 bg-emerald-50',
        },
    ]

    return (
        <div className="card overflow-hidden">
            {/* Top accent gradient */}
            <div className="h-1 bg-gradient-to-r from-blue-500 via-indigo-500 to-violet-500" />

            <div className="p-8 sm:p-10 space-y-8">
                {/* Header — continuity, not error */}
                <div className="text-center space-y-3 max-w-lg mx-auto">
                    <div className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full bg-gradient-to-r from-blue-50 to-indigo-50 border border-blue-100 text-blue-700 text-xs font-semibold uppercase tracking-wider">
                        <TrendingUp className="w-3.5 h-3.5" />
                        You&apos;re on a roll
                    </div>
                    <h2 className="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">
                        Your pipeline is growing.
                        <br />
                        <span className="bg-clip-text text-transparent bg-gradient-to-r from-blue-600 to-indigo-600">
                            Keep the momentum going.
                        </span>
                    </h2>
                    <p className="text-sm text-slate-500 leading-relaxed">
                        You&apos;ve built real traction with AI Prospect Engine. Unlock more credits to scale what&apos;s already working — your leads, scores, and messages are all saved.
                    </p>
                </div>

                {/* Achievements grid */}
                <div className="grid grid-cols-2 sm:grid-cols-4 gap-4">
                    {achievements.map((a) => (
                        <div key={a.label} className="flex flex-col items-center gap-2 p-4 rounded-xl bg-slate-50/50 border border-slate-100">
                            <div className={`w-10 h-10 rounded-lg flex items-center justify-center ${a.color}`}>
                                <a.icon className="w-5 h-5" />
                            </div>
                            <span className="text-2xl font-extrabold text-slate-900 tabular-nums">{a.value}</span>
                            <span className="text-xs text-slate-500 text-center font-medium">{a.label}</span>
                        </div>
                    ))}
                </div>

                {/* Divider with social proof */}
                <div className="flex items-center gap-4">
                    <div className="flex-1 h-px bg-slate-200" />
                    <span className="text-xs text-slate-400 font-medium whitespace-nowrap">
                        Trusted by 200+ B2B teams
                    </span>
                    <div className="flex-1 h-px bg-slate-200" />
                </div>

                {/* CTAs */}
                <div className="flex flex-col sm:flex-row items-center gap-3 max-w-md mx-auto">
                    <a
                        href="/settings#upgrade"
                        className="btn-primary w-full sm:w-auto flex items-center justify-center gap-2 h-12 px-8 text-base shadow-lg shadow-blue-500/25"
                    >
                        <Zap className="w-4 h-4" />
                        Upgrade Plan
                    </a>
                    <a
                        href="/settings#credits"
                        className="btn-secondary w-full sm:w-auto flex items-center justify-center gap-2 h-12 px-8 text-base"
                    >
                        <CreditCard className="w-4 h-4" />
                        Buy Credits
                    </a>
                </div>

                {/* Reassurance */}
                <div className="flex items-center justify-center gap-6 text-xs text-slate-400">
                    <span className="flex items-center gap-1">
                        <ArrowRight className="w-3 h-3" /> Cancel anytime
                    </span>
                    <span className="flex items-center gap-1">
                        <ArrowRight className="w-3 h-3" /> Credits never expire
                    </span>
                    <span className="flex items-center gap-1">
                        <ArrowRight className="w-3 h-3" /> Data always yours
                    </span>
                </div>
            </div>
        </div>
    )
}
